use_frameworks!

platform :ios, '10.0'

target 'GGXRSA_Example' do
  pod 'GGXRSA', :path => '../'

#  target 'GGXRSA_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
